name: pre-build action

description: Installs application and related packages

inputs:
  node_version:
    description: 'Optional input to set the version of Node.js used to build the project.'
    default: '22.x'
  node_caching:
    description: 'Optional input to set up caching for the setup-node action.'
    default: 'pnpm'

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: setup node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.node_caching }}

    - name: install dependencies
      run: pnpm install
      shell: bash

    - name: run linter
      run: pnpm run lint
      shell: bash

    - name: run commit linter
      run: pnpm prepare
      shell: bash
