name: pre-build action

description: Installs application and related packages

inputs:
  node_version:
    description: 'Optional input to set the version of Node.js used to build the project.'
    default: '22.x'
  node_caching:
    description: 'Optional input to set up caching for the setup-node action.'
    default: 'pnpm'
  node_version_file:
    description: 'Optional input to set up npm.'
    default: '.nvmrc'
  registry-url:
    description: 'Optional input to set up npm.'
    default: 'https://registry.npmjs.org'

runs:
  using: composite
  steps:
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: setup node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.node_caching }}
        registry-url: https://registry.npmjs.org

    - name: install dependencies
      run: pnpm install
      shell: bash

    - name: run linter
      run: pnpm run lint
      shell: bash

    - name: run commit linter
      run: pnpm prepare
      shell: bash
